#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 21 19:13:32 2020
"""

import os, sys, shutil

#Constants
SCENAR_ARGUMENTS = {"NON_CONVERGENT":"-incremental -T 30",\
                    "DELTA2":"-convergent -T 100 -Delta 2 ",\
		    "DELTA4":"-convergent -T 100 -Delta 4 ",\
                    "DELTA6":"-convergent -T 100 -Delta 6 ",\
                    "DELTA8":"-convergent -T 100 -Delta 8 ",\
		    "DELTA10":"-convergent -T 100 -Delta 10 "}

N_RUN=5
RUNNABLE="java -jar build/amlsi.jar"
PROPERTIES="properties_files/config.properties"
#Fonction for one experiment
def run(domain, domain_name, initial_state, scenar, rep):
    command = ("%s %s -t RPNIR -properties %s -d %s -o %s -n %s -i %s -r %d") % \
                (RUNNABLE,\
                 SCENAR_ARGUMENTS[scenar],\
                 PROPERTIES,\
                 rep,\
                 domain,\
                 domain_name,\
                 initial_state,\
                 N_RUN)
    print(command)
    os.system("%s > %s/log.txt" % (command, rep))


#Test all scenari
def test(domain, domain_name, base_dir):
    domain_rep="pddl/%s" % domain
    reference="%s/domain.pddl" % domain_rep
    learnt_rep="%s/%s" % (base_dir, domain)

    if(os.path.isdir(learnt_rep)):
        shutil.rmtree(learnt_rep)
    os.mkdir(learnt_rep)

    for scenar in ["NON_CONVERGENT"]:
        rep = "%s/%s" % (learnt_rep , scenar)
        os.mkdir(rep)
        for i in [1,2,3]:
            rep_is = "%s/IS%d" % (rep, i)
            os.mkdir(rep_is)
            initial_state= "%s/initial_states/initial%d.pddl" % (domain_rep, i)
            run(reference, domain_name, initial_state, scenar, rep_is)

    rep_conv = "%s/Delta" % (learnt_rep)
    os.mkdir(rep_conv)
    scenar="DELTA"
    for delta in [2,4,6,8,10]:
        rep = "%s/Delta%d" % (rep_conv , delta)
        os.mkdir(rep)
        for i in [1,2,3]:
            rep_is = "%s/IS%d" % (rep, i)
            os.mkdir(rep_is)
            initial_state= "%s/initial_states/initial%d.pddl" % (domain_rep, i)
            s = "%s%d" % (scenar, delta)
            run(reference, domain_name, initial_state, s, rep_is)

def main():
    print("Begin test")
    test(sys.argv[1], sys.argv[2], sys.argv[3])

if __name__ == "__main__":
    main()

