#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os, sys, shutil
#Constants
PROG="./planner/bin/plan.py"

#Try to plan
def plan(domain, problem, type="seq"):
    command = ("%s %s %s %s --time 600 --validate --no-iterated > /dev/null 2> /dev/null") % (PROG, type, domain,problem)
    code = os.system(command)
    return code

def test(domain, type="seq"):
    domain_rep="pddl/temporal/%s" % domain
    reference="%s/domain.pddl" % domain_rep
    os.system("rm -rf %s/reference" % domain_rep)
    os.mkdir("%s/reference" % domain_rep)
    rep_plan= "%s/reference/plans" % domain_rep
    os.mkdir(rep_plan)
    dfile = ("pddl/temporal/%s/domain.pddl" % (domain))

    for problem in range(1,21):
        pfile = ("pddl/temporal/%s/instances/instance-%d.pddl" % (domain,problem))

        #print(command)
        code_return = plan(dfile, pfile, type)
        if(code_return == 0):
            os.system("cat tmp_sas_plan.1 > %s/plan_%d 2> /dev/null " % (rep_plan, problem))
            if(code_return == 0):
                continue
            else:
                os.system("echo \"NO SOLUTION\" > %s/plan_%d " % (rep_plan, problem))
        else:
            os.system("echo \"NO SOLUTION\" > %s/plan_%d " % (rep_plan, problem))

def main():
    test(sys.argv[1], sys.argv[2])

if __name__ == "__main__":
    main()
